use_modular_headers!

use_frameworks! :linkage => :static

platform :ios, '10.0'

target 'AMSDK-iOS_Example' do
  pod 'AMSDK-iOS', :path => '../'

  target 'AMSDK-iOS_Tests' do
    inherit! :search_paths

    
  end
end
